(() => {
  const config = window.BARON_SUPABASE_CONFIG;
  if (!config || !window.supabase?.createClient) return;
  const client = window.supabase.createClient(config.url, config.publishableKey, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  window.baronSupabase = client;
  const MANAGEMENT_EMAIL = 'mgt.baroncorporation@gmail.com';
  const setMessage=(form,message,kind='success')=>{let box=form?.querySelector(kind==='error'?'.form-error':'.form-success');if(!box&&form){box=document.createElement('div');box.className=kind==='error'?'form-error':'form-success';form.appendChild(box)}if(box){box.textContent=message;box.style.display='block'}};
  const destinationFor=user=>user?.email?.toLowerCase()===MANAGEMENT_EMAIL?'management.html':'applicant-portal.html';
  async function setupSignIn(){const form=document.getElementById('signInForm');if(!form)return;const params=new URLSearchParams(location.search);form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button[type=submit]');b.disabled=true;b.textContent='Signing in...';const {data,error}=await client.auth.signInWithPassword({email:form.email.value.trim(),password:form.password.value});if(error){setMessage(form,error.message,'error');b.disabled=false;b.textContent='Sign In';return}const requested=params.get('redirect');const allowed=['management.html','applicant-portal.html'];location.href=allowed.includes(requested)?requested:destinationFor(data.user)})}
  async function setupCreate(){const form=document.getElementById('createAccountForm');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const p=form.password.value,c=form.confirm_password.value;if(p!==c)return setMessage(form,'Passwords do not match.','error');if(p.length<8||!/[a-z]/.test(p)||!/[A-Z]/.test(p)||!/[0-9]/.test(p))return setMessage(form,'Use at least 8 characters with uppercase, lowercase, and a number.','error');const b=form.querySelector('button[type=submit]');b.disabled=true;b.textContent='Creating account...';const {data,error}=await client.auth.signUp({email:form.email.value.trim(),password:p,options:{emailRedirectTo:'https://baroncorporation.space/sign-in.html?verified=1',data:{account_type:'applicant',first_name:form.first_name.value.trim(),last_name:form.last_name.value.trim(),full_name:`${form.first_name.value.trim()} ${form.last_name.value.trim()}`}}});if(error){setMessage(form,error.message,'error');b.disabled=false;b.textContent='Create Account';return}if(data.session)location.href=destinationFor(data.user);else{setMessage(form,'Account created. Check your email to confirm your address, then sign in.');form.reset();b.disabled=false;b.textContent='Create Account'}})}
  async function protectApplicant(){if(document.body.dataset.portal!=='applicant')return;const {data}=await client.auth.getSession();if(!data.session){location.replace('sign-in.html?redirect=applicant-portal.html');return}document.querySelectorAll('[data-user-email]').forEach(el=>el.textContent=data.session.user.email||'');document.querySelectorAll('[data-sign-out]').forEach(el=>el.onclick=async e=>{e.preventDefault();await client.auth.signOut();location.href='index.html'})}
  document.addEventListener('DOMContentLoaded',()=>{setupSignIn();setupCreate();protectApplicant()});
})();
