(() => {
  const cfg=window.BARON_SUPABASE_CONFIG;
  if(!cfg||!window.supabase?.createClient)return;
  const db=window.baronSupabase||window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true}});
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let jobs=[];
  const jobUrl=j=>`job.html?id=${encodeURIComponent(j.id)}`;
  const applyUrl=j=>`apply.html?job=${encodeURIComponent(j.id)}`;
  const locationText=j=>[j.location_city,j.location_state].filter(Boolean).join(', ')||'United States';
  function card(j){return `<article class="job-card"><div class="job-card-top"><span class="job-tag">${esc(j.category||'Opportunity')}</span><span class="text-link">${esc(j.employment_type||'')}</span></div><div><h3>${esc(j.title)}</h3><div class="job-company">${esc(j.employer_name)}</div></div><div class="job-meta"><span>${esc(locationText(j))}</span>${j.workplace_type?`<span>${esc(j.workplace_type)}</span>`:''}${j.experience_level?`<span>${esc(j.experience_level)}</span>`:''}</div><p>${esc(j.summary||j.description||'View the full opportunity for details.')}</p><div class="job-card-footer"><b>${esc(j.compensation_text||'Compensation listed in details')}</b><a class="text-link" href="${jobUrl(j)}">View job</a></div></article>`}
  async function load(){const {data,error}=await db.from('jobs').select('*').eq('is_active',true).order('created_at',{ascending:false});if(error)throw error;jobs=data||[];return jobs}
  function matches(j,q,state,type){q=q.trim().toLowerCase();const hay=[j.title,j.employer_name,j.category,j.keywords,j.location_city,j.location_state,j.description].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state||j.location_state===state)&&(!type||j.employment_type===type)}
  function renderGrid(el,list){if(!el)return;if(!list.length){el.innerHTML='<div class="empty-state"><h3>No matching opportunities yet</h3><p>Try a broader job title or location. New U.S. opportunities will appear here as they are published.</p></div>';return}el.innerHTML=list.map(card).join('')}
  function bindAutocomplete(input,panel,stateEl){if(!input||!panel)return;const render=()=>{const q=input.value.trim().toLowerCase();if(!q){panel.classList.add('hidden');return}const state=stateEl?.value||'';const list=jobs.filter(j=>matches(j,q,state,'')).slice(0,8);if(!list.length){panel.innerHTML='<div style="padding:13px 16px;font-size:12px;color:#6c7888">No matching published jobs</div>';panel.classList.remove('hidden');return}panel.innerHTML=list.map(j=>`<a href="${jobUrl(j)}"><div><b>${esc(j.title)}</b><span>${esc(j.employer_name)}</span></div><span>${esc(locationText(j))}</span></a>`).join('');panel.classList.remove('hidden')};input.addEventListener('input',render);stateEl?.addEventListener('change',render);document.addEventListener('click',e=>{if(!panel.contains(e.target)&&e.target!==input)panel.classList.add('hidden')})}
  async function home(){const grid=document.getElementById('featuredJobs');if(!grid)return;try{await load();renderGrid(grid,jobs.slice(0,6));const i=document.getElementById('heroKeyword'),s=document.getElementById('heroState'),p=document.getElementById('heroAutocomplete');bindAutocomplete(i,p,s);document.getElementById('heroSearch')?.addEventListener('submit',e=>{e.preventDefault();const qs=new URLSearchParams();if(i.value.trim())qs.set('q',i.value.trim());if(s.value)qs.set('state',s.value);location.href=`jobs.html?${qs}`});document.querySelectorAll('[data-popular]').forEach(b=>b.addEventListener('click',()=>{location.href=`jobs.html?q=${encodeURIComponent(b.dataset.popular)}`}))}catch(err){renderGrid(grid,[])} }
  async function listing(){const grid=document.getElementById('jobsGrid');if(!grid)return;const qEl=document.getElementById('jobsKeyword'),sEl=document.getElementById('jobsState'),tEl=document.getElementById('jobsType'),count=document.getElementById('resultsCount'),panel=document.getElementById('jobsAutocomplete');const params=new URLSearchParams(location.search);qEl.value=params.get('q')||'';sEl.value=params.get('state')||'';try{await load();bindAutocomplete(qEl,panel,sEl);const apply=()=>{const list=jobs.filter(j=>matches(j,qEl.value,sEl.value,tEl.value));renderGrid(grid,list);if(count)count.textContent=`${list.length} opportunity${list.length===1?'':'ies'}`};[qEl,sEl,tEl].forEach(el=>el.addEventListener(el===qEl?'input':'change',apply));document.getElementById('jobsFilterForm')?.addEventListener('submit',e=>{e.preventDefault();apply()});apply()}catch(e){renderGrid(grid,[]);if(count)count.textContent='Marketplace setup pending'} }
  async function detail(){const root=document.getElementById('jobDetail');if(!root)return;const id=new URLSearchParams(location.search).get('id');if(!id){root.innerHTML='<div class="empty-state"><h3>Job not found</h3></div>';return}const {data:j,error}=await db.from('jobs').select('*').eq('id',id).eq('is_active',true).maybeSingle();if(error||!j){root.innerHTML='<div class="empty-state"><h3>This opportunity is unavailable</h3><p>It may have closed or the link may be incorrect.</p></div>';return}document.title=`${j.title} | Baron Jobs`;const arr=v=>Array.isArray(v)?v:[];root.innerHTML=`<section class="detail-hero"><div class="container"><span class="eyebrow">${esc(j.category||'Job opportunity')}</span><h1 class="detail-title">${esc(j.title)}</h1><div class="detail-sub"><span>${esc(j.employer_name)}</span><span>${esc(locationText(j))}</span><span>${esc(j.employment_type||'')}</span><span>${esc(j.workplace_type||'')}</span></div></div></section><div class="container detail-shell"><article class="detail-main"><p>${esc(j.description||j.summary||'')}</p>${arr(j.responsibilities).length?`<h2>Responsibilities</h2><ul>${arr(j.responsibilities).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${arr(j.requirements).length?`<h2>Requirements</h2><ul>${arr(j.requirements).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${arr(j.benefits).length?`<h2>Benefits</h2><ul>${arr(j.benefits).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<div class="notice">Do not submit Social Security numbers, banking information, passwords, or payment details in an application.</div></article><aside class="detail-side"><span class="eyebrow">Opportunity overview</span><h3>${esc(j.compensation_text||'Compensation details')}</h3><p>${esc(locationText(j))}</p><p>${esc(j.employment_type||'')}</p><p>${esc(j.experience_level||'')}</p><a class="btn btn-gold btn-full" href="${applyUrl(j)}">Apply Now</a><p style="font-size:11px;color:#6c7888">After you apply, your submission enters review. Any next steps will continue by email.</p></aside></div>`}
  async function apply(){const form=document.getElementById('applicationForm');if(!form)return;const id=new URLSearchParams(location.search).get('job');const box=document.getElementById('selectedJob');const submit=form.querySelector('button[type=submit]');if(!id){box.textContent='No job selected.';submit.disabled=true;return}const {data:j,error}=await db.from('jobs').select('*').eq('id',id).eq('is_active',true).maybeSingle();if(error||!j){box.textContent='This opportunity is no longer available.';submit.disabled=true;return}box.innerHTML=`<b>${esc(j.title)}</b><span>${esc(j.employer_name)} · ${esc(locationText(j))}</span>`;form.job_id.value=j.id;form.job_title_snapshot.value=j.title;form.addEventListener('submit',async e=>{e.preventDefault();const errBox=form.querySelector('.form-error');errBox.style.display='none';if(form.website.value)return;submit.disabled=true;submit.textContent='Submitting application...';const {data:sess}=await db.auth.getSession();const payload={job_id:j.id,job_title_snapshot:j.title,first_name:form.first_name.value.trim(),last_name:form.last_name.value.trim(),email:form.email.value.trim(),phone:form.phone.value.trim(),city:form.city.value.trim(),state:form.state.value,years_experience:form.years_experience.value?Number(form.years_experience.value):null,recent_job_title:form.recent_job_title.value.trim()||null,certification:form.certification.value.trim()||null,availability:form.availability.value.trim()||null,professional_summary:form.professional_summary.value.trim(),additional_info:form.additional_info.value.trim()||null,consent:form.consent.checked,user_id:sess.session?.user?.id||null};const {error:insertError}=await db.from('applications').insert(payload);if(insertError){errBox.textContent='Your application could not be submitted right now. Please try again.';errBox.style.display='block';submit.disabled=false;submit.textContent='Submit Application';return}location.href=`application-confirmation.html?job=${encodeURIComponent(j.title)}`})}
  document.addEventListener('DOMContentLoaded',()=>{home();listing();detail();apply()});
})();
