(() => {
  const cfg=window.BARON_SUPABASE_CONFIG;if(!cfg||!window.supabase?.createClient)return;
  const db=window.baronSupabase||window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true}});const EMAIL='mgt.baroncorporation@gmail.com';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function init(){const shell=document.getElementById('managementShell');if(!shell)return;const {data}=await db.auth.getSession();const user=data.session?.user;if(!user){location.replace('sign-in.html?redirect=management.html');return}if(user.email?.toLowerCase()!==EMAIL){shell.innerHTML='<div class="empty-state"><h3>Management access only</h3><p>This account is not authorized to manage job listings or applications.</p></div>';return}document.getElementById('managementEmail').textContent=user.email;document.getElementById('adminSignOut').onclick=async()=>{await db.auth.signOut();location.href='index.html'};bindTabs();bindJobForm();await Promise.all([loadJobs(),loadApplications()])}
  function bindTabs(){document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('[data-tab-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.tabPanel!==b.dataset.tab))})}
  function lines(v){return v.split('\n').map(x=>x.trim()).filter(Boolean)}
  function bindJobForm(){const form=document.getElementById('jobAdminForm');form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Publishing...';const payload={title:form.title.value.trim(),employer_name:form.employer_name.value.trim(),location_city:form.location_city.value.trim(),location_state:form.location_state.value,workplace_type:form.workplace_type.value,employment_type:form.employment_type.value,category:form.category.value.trim(),experience_level:form.experience_level.value,compensation_text:form.compensation_text.value.trim()||null,summary:form.summary.value.trim(),description:form.description.value.trim(),keywords:form.keywords.value.trim()||null,responsibilities:lines(form.responsibilities.value),requirements:lines(form.requirements.value),benefits:lines(form.benefits.value),is_active:true};const {error}=await db.from('jobs').insert(payload);if(error){alert(error.message)}else{form.reset();await loadJobs()}btn.disabled=false;btn.textContent='Publish Job'})}
  async function loadJobs(){const wrap=document.getElementById('adminJobs');const {data,error}=await db.from('jobs').select('*').order('created_at',{ascending:false});if(error){wrap.innerHTML='<p>Could not load jobs.</p>';return}wrap.innerHTML=(data||[]).map(j=>`<div class="admin-item"><div class="admin-item-top"><div><h3>${esc(j.title)}</h3><p>${esc(j.employer_name)} · ${esc([j.location_city,j.location_state].filter(Boolean).join(', '))}</p></div><span class="status-pill ${j.is_active?'active':''}">${j.is_active?'Published':'Hidden'}</span></div><div class="admin-actions"><button data-toggle-job="${j.id}" data-active="${j.is_active}">${j.is_active?'Hide':'Publish'}</button><button class="danger" data-delete-job="${j.id}">Delete</button></div></div>`).join('')||'<div class="empty-state"><p>No jobs published yet.</p></div>';wrap.querySelectorAll('[data-toggle-job]').forEach(b=>b.onclick=async()=>{await db.from('jobs').update({is_active:b.dataset.active!=='true'}).eq('id',b.dataset.toggleJob);loadJobs()});wrap.querySelectorAll('[data-delete-job]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this job listing?')){await db.from('jobs').delete().eq('id',b.dataset.deleteJob);loadJobs()}})}
  async function loadApplications(){const wrap=document.getElementById('adminApplications');const {data,error}=await db.from('applications').select('*,jobs(title,employer_name)').order('created_at',{ascending:false});if(error){wrap.innerHTML='<p>Could not load applications.</p>';return}wrap.innerHTML=(data||[]).map(a=>{const name=`${a.first_name} ${a.last_name}`.trim();const subject=encodeURIComponent(`Baron Corporation application update - ${a.job_title_snapshot}`);const body=encodeURIComponent(`Hello ${name},\n\nThank you for your application for ${a.job_title_snapshot}. We are contacting you regarding the next step in the review process.\n\nRegards,\nBaron Corporation`);return `<div class="admin-item"><div class="admin-item-top"><div><h3>${esc(name)}</h3><p>${esc(a.job_title_snapshot)} · ${esc(a.city)}, ${esc(a.state)}</p><p>${esc(a.email)} · ${esc(a.phone||'No phone')}</p></div><span class="status-pill">Waiting review</span></div><p><b>Experience:</b> ${esc(a.years_experience??'Not stated')} year(s) · ${esc(a.recent_job_title||'No recent title')}</p><p>${esc(a.professional_summary)}</p>${a.certification?`<p><b>Certification:</b> ${esc(a.certification)}</p>`:''}<div class="admin-actions"><a href="mailto:${encodeURIComponent(a.email)}?subject=${subject}&body=${body}">Email applicant</a></div></div>`}).join('')||'<div class="empty-state"><p>No applications submitted yet.</p></div>'}
  document.addEventListener('DOMContentLoaded',init);
})();
